#!/bin/sh

URL_PRE="https://mlcs.medu.com/api/b2_registration/refresh_info?q=&carrier_code=&carrier_name=&device_name=&platform=&client_id="
URL_POST="&timestamp=&registration_id=&f=xml&device_id=&android=1&v=1&language=en_GB&ver=3.1.2"
MAX_CLIENT_ID=10 #22000
showBar() {
    width=$((`tput cols` - 10 - 6))
    percent=$(( 100 * $1 / $2 ))
    printf "\r%3d%% [" $percent 1>&2

    # print progress bar
    bar=$((($width * $1) / $2))
    if [ "$bar" -gt "0" ]; then
        for i in $(seq 1 $bar); do printf "=" 1>&2; done
    fi
    if [ "$1" -ne "$2" ]; then
        printf ">"
        for i in $(seq $bar $(( $width))); do printf " " 1>&2; done
    else
        printf "=="
    fi
    printf "] %6d" $1 1>&2
}

OUTPUT_XML_FILE="output.xml"
FAILURE_FILE="badIds.md"
OUTPUT_MARKDOWN_FILE="output.md"

if [ -n "$1" ]; then
    OUTPUT_XML_FILE="$1"
fi
if [ -n "$2" ]; then
    FAILURE_FILE="$2"
fi
if [ -n "$3" ]; then
    OUTPUT_MARKDOWN_FILE="$3"
fi

mkdir raw > /dev/null 2>&1
mkdir temp > /dev/null 2>&1

clear
showBar 0 $MAX_CLIENT_ID

###XML FILE INIT
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<data>" > "$OUTPUT_XML_FILE"

###FAILURE FILE INIT
echo "Client ID's With No Support" > "$FAILURE_FILE"
echo "===========================" >> "$FAILURE_FILE"


for CLIENT_ID in $(seq 0 $MAX_CLIENT_ID); do
    TEMP_OUTPUT=`curl -s "$URL_PRE$CLIENT_ID$URL_POST"`
    if echo "$TEMP_OUTPUT" | fgrep -q "<s>" -; then
        echo "$TEMP_OUTPUT" | grep "[\\s]*<[^?].*$" - >> "$OUTPUT_XML_FILE"
        echo "$TEMP_OUTPUT" > "raw/$CLIENT_ID.xml"
        UNI_NAME=`echo "$TEMP_OUTPUT" | sed -n "s|<name>\(<\!\[CDATA\[\)\{0,1\}\([^]<]*\)\(]]>\)\{0,1\}</name>|\2|p"`
        B2_URL=`echo "$TEMP_OUTPUT" | sed -n "s|<b2_url>\(.*\)</b2_url>|\1|p"`
        echo " - $UNI_NAME(\`client_id=$CLIENT_ID\`) => \`[$B2_URL]($B2_URL)\`" > "temp/$UNI_NAME.md"
    else
        echo " - $CLIENT_ID" >> "$FAILURE_FILE"
    fi
    showBar $CLIENT_ID $MAX_CLIENT_ID
done
echo "</data>" >> "$OUTPUT_XML_FILE"

echo "Downloading Complete."

echo "#Provider Names with Client IDs#\n" > "$OUTPUT_MARKDOWN_FILE"
echo "**This file is automatically generated.**\n" >> "$OUTPUT_MARKDOWN_FILE"



echo "##Table Of Contents##" >> "$OUTPUT_MARKDOWN_FILE"
echo " - Provider Names with Client IDs" >> "$OUTPUT_MARKDOWN_FILE"

LAST_FIRST_CHARACTER=""
IFS='
'
rm "temp/finalFile.md"
FILES=$(ls -1 temp/ )
for FILE_NAME in $(echo "$FILES"); do
    if [ "$FILE_NAME" != "finalFile.md" ]; then
        FIRST_CHARACTER=`echo "$FILE_NAME" | sed "s|^\(.\).*|\1|"`
        if [ "$LAST_FIRST_CHARACTER" != "$FIRST_CHARACTER" ]; then
            LAST_FIRST_CHARACTER="$FIRST_CHARACTER"
            echo "<a name=\"$FIRST_CHARACTER\"></a>" >> "temp/finalFile.md"
            echo "##$FIRST_CHARACTER##\n" >> "temp/finalFile.md"
        fi
        cat "temp/$FILE_NAME" >> "temp/finalFile.md"
    fi
done

grep "[#]\+" "temp/finalFile.md" | sed -e "s|#\{1\}| |g" -e "s|\([^ ]\)[ ]*$|\1|" -e "s|\([ ]*\)\(.*\)|\1 - <a href=\"#\2\">\2</a>|" >> "$OUTPUT_MARKDOWN_FILE"
echo "---------------------"
cat "temp/finalFile.md" >> "$OUTPUT_MARKDOWN_FILE"

rm -rf "temp/" > /dev/null 2>&1



echo "Done"